name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
  
   gcc project_main.c src/calculator_operations.c  -Iinc -o build/Calculator.out.out
